@startuml c4-1-context
!include <C4/C4_Context>

Person(admin, "Admin")
Person(user, "User")

System(system, "Unicorn Webshop", "Webshop offering unicorn themed products.") 
System_Ext(inventory, "Inventory System", "Web Application tracking the inventory in store.")
System_Ext(payment, "Payment Provider", "Provides secure payment services.")
System_Ext(email, "E-Mail System", "Microsoft Exchange e-mail system.")



Rel_D(user, system, "Search, select and order products. Set-up payment.")
Rel_D(admin, system, "Administer webshop configurations.")

Rel(system, inventory, "Get current stock information for products.", "REST")
Rel(system, payment, "Execute payment.", "REST")
Rel(system, email, "Send emails.")

Rel_U(email, user, "Send order information.")

@enduml
