name: Render PlantUML diagrams

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  render-plantuml:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: |
          sudo apt install graphviz
          wget https://github.com/plantuml/plantuml/releases/download/v1.2024.7/plantuml-1.2024.7.jar

      - name: Render PlantUML diagrams
        run: |
          java -jar plantuml-1.2024.7.jar C4/*.puml
          mv C4/*.png images/  

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
  
      - name: Push generated image
        if: steps.changed-files.outputs.all_changed_files_count > 0
        env:
          ALL_CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
        run: |
          echo "$ALL_CHANGED_FILES_COUNT have changed"
          cd images
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git remote set-url --push origin https://iris-hunkeler:$GITHUB_TOKEN@github.com/iris-hunkeler/architecture-documentation
          git add *.png
          git commit -m "Update generated image(s)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
