name: Render PlantUML diagrams

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  render-plantuml:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: |
          sudo apt install graphviz
          wget https://github.com/plantuml/plantuml/releases/download/v1.2024.7/plantuml-1.2024.7.jar

      - name: Render PlantUML diagrams
        run: |
          java -jar plantuml-1.2024.7.jar C4/*.puml
          mv C4/*.png images/  

      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only | xargs)"
  
      - name: Push generated image
        if: ${{needs.changedfiles.outputs.ts}}
        run: |
          cd images
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git remote set-url --push origin https://iris-hunkeler:$GITHUB_TOKEN@github.com/iris-hunkeler/architecture-documentation
          git add *.png
          git commit -m "Update generated image(s)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
