name: Render PlantUML diagrams

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  render-plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: |
          sudo apt install graphviz
          wget https://github.com/plantuml/plantuml/releases/download/v1.2024.7/plantuml-1.2024.7.jar

      - name: Render PlantUML diagrams
        run: java -jar plantuml-1.2024.7.jar C4/*.puml

      - name: Push generated image
        run: |
          mv C4/*.png images/
          cd images
          git remote set-url --push origin https://iris-hunkeler:$GITHUB_TOKEN@github.com/github.com/iris-hunkeler/architecture-documentation
          git add *.png
          git commit -m "Update generated image(s)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
