name: Render PDF from Markdown
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Render PlantUML diagrams]
    types:
      - completed

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository      
        uses: actions/checkout@v3
      - name: Generate PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false

      - name: Get changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
  
      - name: Push generated image
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd images
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git remote set-url --push origin https://iris-hunkeler:$GITHUB_TOKEN@github.com/iris-hunkeler/architecture-documentation
          git add *.pdf
          git commit -m "Update generated pdf(s)"
          git push origin main         
